### ISSUE TITLE
填充颜色

### ISSUE THREAD

**Issue by LanJingH** [CC4J/fabric-drawing-board#1]
大佬，点击  根据线条拼接出的图形，填充颜色，这块如何实现

**Comment by LanJingH** [comment]
> 点击 根据线条拼接出的图形，填充颜色

**Comment by CC4J** [comment]
填充颜色用在 矩形，圆形上，用自由画笔绘制出来的，你想填充颜色，就更改自由画笔的颜色，自己去一笔一笔的补满，哈哈。

**Comment by CC4J** [comment]
> 大佬，点击 根据线条拼接出的图形，填充颜色，这块如何实现

填充颜色用在 矩形，圆形上，用自由画笔绘制出来的，你想填充颜色，就更改自由画笔的颜色，自己去一笔一笔的补满，哈哈。

**Comment by CC4J** [comment]
> 大佬，点击 根据线条拼接出的图形，填充颜色，这块如何实现

我将功能封装成了一个npm包  ，npm上 搜索 fabric-drawing-board。让你使用起来更简单哟

**Comment by LanJingH** [comment]
帅哥，如果我用画笔画了两个不同图形，如何获取点击的是哪个图形？然后根据点击的图形上色？
