### ISSUE TITLE
获取图形

### ISSUE THREAD

**Issue by LanJingH** [CC4J/fabric-drawing-board#2]
帅哥，如果我用画笔画了两个不同图形，如何获取点击的是哪个图形？然后根据点击的图形上色？

**Comment by CC4J** [comment]
> 帅哥，如果我用画笔画了两个不同图形，如何获取点击的是哪个图形？然后根据点击的图形上色？

fabric可以给画布监听点击事件，在事件回调里可以获取到当前选择的图形对象，拿到图形对象了自然就可以通过fabric提供的api去修改他的线框色与填充色。你可以去看一下 fabric的文档。如果你只想实现一个简单的画板功能，推荐你使用我封装后的 npm包  fabric-drawing-board ：）

**Comment by LanJingH** [comment]
好的，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CC4J/fabric-drawing-board"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 上午9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CC4J/fabric-drawing-board] 获取图形 (#2)





  
帅哥，如果我用画笔画了两个不同图形，如何获取点击的是哪个图形？然后根据点击的图形上色？
  
fabric可以给画笔监听点击事件，在事件回调里可以获取到当前选择的图形对象，那道图形对象了自然就可以通过fabric提供的api去修改他的线框色与填充色。你可以去看一下 fabric的文档。如果你只想实现一个简单的画板功能，推荐你使用我封装后的 npm包  fabric-drawing-board ：）

**Comment by CC4J** [comment]
> 好的，感谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CC4J/fabric-drawing-board" ***@***.***&gt;; 发送时间:&nbsp;2021年7月22日(星期四) 上午9:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CC4J/fabric-drawing-board] 获取图形 (#2) 帅哥，如果我用画笔画了两个不同图形，如何获取点击的是哪个图形？然后根据点击的图形上色？ fabric可以给画笔监听点击事件，在事件回调里可以获取到当前选择的图形对象，那道图形对象了自然就可以通过fabric提供的api去修改他的线框色与填充色。你可以去看一下 fabric的文档。如果你只想实现一个简单的画板功能，推荐你使用我封装后的 npm包 fabric-drawing-board ：） — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不客气，如果觉得对你有些帮助，麻烦给个 star ，(●'◡'●)

**Comment by CC4J** [comment]
> 好的，感谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CC4J/fabric-drawing-board" ***@***.***&gt;; 发送时间:&nbsp;2021年7月22日(星期四) 上午9:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CC4J/fabric-drawing-board] 获取图形 (#2) 帅哥，如果我用画笔画了两个不同图形，如何获取点击的是哪个图形？然后根据点击的图形上色？ fabric可以给画笔监听点击事件，在事件回调里可以获取到当前选择的图形对象，那道图形对象了自然就可以通过fabric提供的api去修改他的线框色与填充色。你可以去看一下 fabric的文档。如果你只想实现一个简单的画板功能，推荐你使用我封装后的 npm包 fabric-drawing-board ：） — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不客气，如果觉得对你有些帮助，麻烦给个 star ，(●'◡'●)

**Comment by LanJingH** [comment]
没得问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CC4J/fabric-drawing-board"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 上午9:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CC4J/fabric-drawing-board] 获取图形 (#2)





  
好的，感谢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CC4J/fabric-drawing-board" @.&gt;; 发送时间:&nbsp;2021年7月22日(星期四) 上午9:02 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CC4J/fabric-drawing-board] 获取图形 (#2) 帅哥，如果我用画笔画了两个不同图形，如何获取点击的是哪个图形？然后根据点击的图形上色？ fabric可以给画笔监听点击事件，在事件回调里可以获取到当前选择的图形对象，那道图形对象了自然就可以通过fabric提供的api去修改他的线框色与填充色。你可以去看一下 fabric的文档。如果你只想实现一个简单的画板功能，推荐你使用我封装后的 npm包 fabric-drawing-board ：） — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
不客气，如果觉得对你有些帮助，麻烦给个 star ，(●'◡'●)
