### ISSUE TITLE
哥们，你有用 fabric 实现复杂图形和交互吗？

### ISSUE THREAD

**Issue by dahui4dev** [CC4J/fabric-drawing-board#3]
如题：复杂图形，比如矩形中带文字，双击编辑文字，等等功能。

**Comment by CC4J** [comment]
> 如题：复杂图形，比如矩形中带文字，双击编辑文字，等等功能。

你可以先画一个矩形，然后在矩形中添加文字。至于双击编辑文字。fabric可以给图形添加点击事件，在点击事件的回调了你可以判断当前图形是否为文字，如果是文字，让文字进入编辑状态即可。如果你想让用户直接绘制一个带文字的图形，也可以，直接在绘制矩形之后通过代码自动在矩形内绘制一段文字即可。

**Comment by dahui4dev** [comment]
能说的再细节一点吗？比如 图形里面怎么加文字？ 因为 fabric Rect 类是不带 文字属性的，想加的话，只能 Rect + Textbox 搞一个 Group ，但是这种交互代码实现很不方便。

**Comment by CC4J** [comment]
> 能说的再细节一点吗？比如 图形里面怎么加文字？ 因为 fabric Rect 类是不带 文字属性的，想加的话，只能 Rect + Textbox 搞一个 Group ，但是这种交互代码实现很不方便。

就是你想的那样，没有更方便的实现形式。你只能自行进行封装。
